services:
  laravel-backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: general/php-8.3
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    ports:
      - "8010:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - laravel-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  laravel-network:
    driver: bridge